### ISSUE TITLE
Add new scale methods

### ISSUE THREAD

**Issue by davidyell** [davidyell/CakePHP3-Proffer#124]
Currently there is no way to scale an uploaded image to a specific size by a specific side.

For example, `['w' => 100]` would just scale the image to 100px wide, regardless.

**Comment by michelpeters** [comment]
I was just thinking about this, because it's something I want/need often. I've used UploadPack in CakePHP2 a lot and I like the compact and easy way it allows to specify the scaling/etc you want to achieve. For example (from the documentation on: https://github.com/szajbus/uploadpack):

> You can specify any of the following resize modes for your styles:
>* *100x80* - resize for best fit into these dimensions, with overlapping edges trimmed if original >aspect ratio differs
>* *[100x80]* - resize to fit these dimensions, with white banding if original aspect ratio differs (Michał's original resize method)
>* *100w* - maintain original aspect ratio, resize to 100 pixels wide
>* *80h* - maintain original aspect ratio, resize to 80 pixels high
>* *80l* - maintain original aspect ratio, resize so that longest side is 80 pixels

Maybe the scaling methods itself could be in a seperate class, so it allows others to extend/override the default behavior of it. I'm aware that currently there is a `ImageTransform` class for parts of this. I was thinking more about specific additional format -> result handlers. So for example a user would like to extend the transformation with something like: (not really realistic example) "^[50x50]" => { ... invert image .. } . ( note the "^" character, here meaning "inverse" ). However, supporting the base scaling like UploadPack is first priority.

**Comment by davidyell** [comment]
Replace Imagine with Intervention.

http://image.intervention.io/api/fit

**Comment by davidyell** [comment]
Closing in favour of #188

**Comment by miguelxt** [comment]
Using this PR https://github.com/miguelxt/CakePHP3-Proffer/pull/1 you are able to call any function directly from Intervention
