### ISSUE TITLE
Why it does not work, if not disabling Security Component?

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#190]
I have installed the Proffer plugin in edit post with multiple images associated.
Why it does not work, if not disabling Security Component?

Disabling Security Component for

```php
  public function beforeFilter(Event $event) {
        $this->Security->config('unlockedActions', ['edit']);
    }
```

**Comment by davidyell** [comment]
I don't understand the question. Please can you clarify what you mean.

**Comment by dacdam** [comment]
I have the same problem.

The case is a table "Products" with a hasMany table "ProductImages" and a form to submit multiple images per time in the product's context.

To have the submit working, I had to disable the security component for the action "edit" in ProductsController.

If not, it was always raised a "missing field" error caused by the tampering protection of the security component.

**Comment by davidyell** [comment]
You could just unlock the fields in question.
https://book.cakephp.org/3.0/en/controllers/components/security.html#form-tampering-prevention

**Comment by dacdam** [comment]
Yes, but for every upload, it is necessary to unlock 6 fields (the one actually added to the form plus the 5 added by the plugin).
It seems like a little annoying to me, I'll do it only in case of real needs.
