### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by novis921111** [davidyell/CakePHP3-Proffer#206]
![why](https://cloud.githubusercontent.com/assets/12060919/18542459/30cc5ce8-7b55-11e6-81bf-2c4126f436cb.JPG)

**Comment by novis921111** [comment]
why is it?

**Comment by davidyell** [comment]
Well `tmp_name` is the name of an uploaded file in the `$_FILES` array, and the fact that `getImageSize()` has no file would lead me to conclude that no file has been uploaded from your form.

There are a number of things I would check, if I was debugging this error.

- Check is that the plugin has been loaded in your `config/bootstrap.php` `Plugin::load('Proffer');`
- Ensure that the behaviour is attached to the Table class using `$this->addBehavior('Proffer.Proffer');`
- Check that your form is a file type form, `$this->Form->create($entity, ['type' => 'file']);`

**Comment by novis921111** [comment]
thank you thank you thank you i missed something in the form but it uploaded now :+1: :) 

anyway is it possible to crop photo that i want to upload before submitting it?

**Comment by davidyell** [comment]
Yes it is. Open it in your favourite graphics editor, crop it, and then submit it on your form.

**Comment by novis921111** [comment]
yes i mean the second one... 
is it this one?
 'square' => [
    'w' => 200,
    'h' => 200,
    'fit' => true
],
'portrait' => [
    'w' => 150,
    'h' => 300,
    'crop' => true
] 

i put it inside thumbnail method in the same level as gd/imagick but i think it's not there because it doesn't work... do i put it in the wrong place?

**Comment by novis921111** [comment]
anyway i got this error when i'm trying to display it using this code ====> echo $this->Html->image('../files/<table>/<field>/' . $data->get('image_dir') . '/<prefix>_' . $data->get('image')); 
do you know what's wrong? in my case i was using photo instead of image

![kasi](https://cloud.githubusercontent.com/assets/12060919/18561875/d9996770-7bab-11e6-9e54-c18dd03afff6.JPG)

**Comment by davidyell** [comment]
Yes you have, [please see the documentation for an example of the array structure](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/configuration.md#configuring-the-behaviour-in-your-table).

**Comment by novicesoyouknow** [comment]
so it's automatic? i did that but i thought there'll be another way to crop it manually.. on upload ofcourse not using photo editor

**Comment by novicesoyouknow** [comment]
i already did put that crop true in thumbnail size and it cropped automatically and stored the original and the cropped square and portrait one... 

i thought i could crop manually on upload and store the cropped one only... but i think it can't.. because database only stored the original one and when i tried to display it, it appears like this..
![foto](https://cloud.githubusercontent.com/assets/12060919/18587582/fb194d38-7c4c-11e6-8580-b1e53000e54d.JPG)

my another failure, again. :( 
maybe you know why the pic doesn't show?

**Comment by davidyell** [comment]
The plugin works by saving the original image to the file system and adding prefixes to that image based on the thumbnails being generated. This way, there is no need to store all the generated image filenames in the database as they can be inferred from the original filename and the thumbnail.

When displaying images, you should [use the Image helper with the correct path as detailed in the documentation](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples.md#displaying-uploaded-images).

**Comment by novicesoyouknow** [comment]
thank you for your patience.. i did all of that and i didn't realize... 
only after leaving for a few days and start to learn again, i found out it was unsync of my database and validation in model table, plus the pic size is just too big... 
and for that cracked image, i was too sleepy to realize that i was trying to display an image of a wrong record... i supposed to call a, the one that i have added a pic, but i called b, the no pic one....  
 
anyway thank you thank you thank you

**Comment by novicesoyouknow** [comment]
if it is not too much to ask... and it's out of upload topic, but i couldn't find any answer yet... 
do you happen to know what should i do with this problem?

- i have 3 tables, forums, comments and users... (it's like post comments and users)
when i open a forum, i want to show the related comments with users' names too, 
but... even tho i can show comment's user_id, i can't show comment's user's name :( 

- also when i open a forum and i want to add comment, how to make it possible to make system automatically choosing that forum, instead of user choosing forum from forums list manually in the add form? 
like automatically choose the logged in user for user_id field (that $this->Auth->user('id') thing), instead of choosing user from users list in add form? 
is it possible?

sorry and thank you

**Comment by davidyell** [comment]
Queries will return either an entity, or an array of entities. So outputting data should be as simple as `echo $form->user->username`.

If you are using `->select()` in your query, you must include all the fields that you want included.

For auto population of forms, I just tend to pass the id of the related record as a query string. So if I was editing a User and wanted to add a new Address, I'd use `example.com/addresses/add?user_id=1`.

**Comment by novicesoyouknow** [comment]
i still don't get that but anyway i'm coming to ask about image again 

while i'm in incomingfund view... i want to show the user's name and photo... so i wrote this : 
![2](https://cloud.githubusercontent.com/assets/12060919/18742332/c8938e6a-80dd-11e6-91bf-946a0a3eecd4.JPG) 
it works well with the name but not with image... it shows photo's file name : 
![1](https://cloud.githubusercontent.com/assets/12060919/18742338/d27cd92c-80dd-11e6-98d9-1bb1fc642936.JPG)

is there a way to show the pic using $this->Html->image so i can display the real image or anything else maybe ? 
because when i tried to that i got this.. 
![3](https://cloud.githubusercontent.com/assets/12060919/18742448/7a39cf6c-80de-11e6-9b82-1ff19e1345e0.JPG)

**Comment by davidyell** [comment]
I've already answered that question in my above comments.
