### ISSUE TITLE
Move Uploaded File fails

### ISSUE THREAD

**Issue by waruna999** [davidyell/CakePHP3-Proffer#211]
version 0.8 brakes image upload
/src/Model/Behavior/ProfferBehavior.php
When line 123 to 127 changed FROM
                    'name' => $entity->get('name'),
                    'type' => $entity->get('type'),
                    'tmp_name' => $entity->get('tmp_name'),
                    'error' => $entity->get('error'),
                    'size' => $entity->get('size'),
TO
                    'name' => $entity->get($field)['name'],
                    'type' => $entity->get($field)['type'],
                    'tmp_name' => $entity->get($field)['tmp_name'],
                    'error' => $entity->get($field)['error'],
                    'size' => $entity->get($field)['size'],
works fine.

**Comment by davidyell** [comment]
Well all the tests pass, so I'm pretty confident that it works.

The only scenario I can think of in which this could happen was that the entity being saved was matched to the repo's entity class. Which in cases where a single field is part of an entity, it wouldn't be because the upload fields are beneath the field.

I'll give it a test though just in case.

**Comment by isemantics** [comment]
I have this issue as well after the new commits done in January. In the meanwhile I will use the older version. 

# Test setup
I've created a fresh new cakephp3 project and "composer require"'d Proffer into the project. Added plugin load to bootstrap.php, created base table for "users" with "image" and "image_dir" (per documentation), baked basic Users entity/model/controller/template. Then modified the add.ctp to have a file input for field "image" and form type = file. Tried to upload a valid PNG (and some other extensions/files, to be sure) and all gave me the same issue I had encoutered in the original project I was working on. 

# Issue
I get the following error message: 
`rename(,M:\Work\www\cake3\webroot\files\users\image\822a9974-22fc-4c1f-b097-073fbcdceb96\logo.png): Invalid argument [ROOT\vendor\davidyell\proffer\src\Model\Behavior\ProfferBehavior.php, line 271]` where we can notice that the first argument for the rename() function is null/empty. 

and sometimes I've seen this one:
`rename(,M:\Work\www\cake3\webroot\files\users\image\20b64e09-6929-4d46-bec2-a8aab07c50a4\logo.png): Cannot create a file when that file already exists. (code: 183) [ROOT\vendor\davidyell\proffer\src\Model\Behavior\ProfferBehavior.php, line 274]`

I guess both have the same origin.

# Proffer behavior in UsersTable
```php
$this->addBehavior('Proffer.Proffer', [
            'image' => [
                'dir' => 'image_dir',
                'thumbnailSizes' => [
                    'thumb' => [
                        'w' => 150,
                        'h' => 150
                    ]
                ],
                'thumbnailMethod' => 'gd'
            ]
        ]);
```

# Form add.ctp code
```php
echo $this->Form->create($user, ['type' => 'file']);
echo $this->Form->input('image', ['type' => 'file']);
echo $this->Form->submit('Save');
echo $this->Form->end();
```

# POST data after submit on add()
It seems the file upload itself (and storage to tmp) works just fine.

```
Debug: Array
(
    [image] => Array
        (
            [name] => logo.png
            [type] => image/png
            [tmp_name] => M:\Work\Server\tmp\php9E44.tmp
            [error] => 0
            [size] => 21165
        )

)
```

# Debug from values in the Proffer code
Same place where the rename() (the error) comes from. This might help you find the issue. It is the same code as the original poster of this issue talked about. At ProfferBehavior.php @ line 115 there is the process() function. Debugging the value $tableEntityClass contains "App\Model\Entity\User" and the $entity is of the same type (tested using `get_class($entity)`). 

This means the following code `if ($tableEntityClass !== null && $entity instanceof $tableEntityClass) {` will be "true" and thus the inside is executed. Which is the same code as the original poster referred to. 
The file data it wants to get with `$entity->get('tmp_name')` et all, is not available at the entity level, but it is in the "image" (array) field in the request data. 

# Testcases
I could not get the testcases to run, because on my system it cannot find the "Stubs". I think this has nothing to do with the testcases, but with my incomplete setup for running the testcases ( probably need to use composer without --prefer-dist ? ).
Specifically the console states: `Proffer\Tests\Model\Behavior\ProfferBehaviorTest::testReplacingComponents
Error: Class 'Proffer\Tests\Stubs\TestPath' not found
`
 
Thanks for your time.

**Comment by davidyell** [comment]
Yeah, it's the `if` statement isn't tight enough to differentiate associated entity from entity data.

[The bug will be here](https://github.com/davidyell/CakePHP3-Proffer/blob/develop/src/Model/Behavior/ProfferBehavior.php#L86-L97) I think, and just needs a tweak to better decide between the two array formats. I tried to simplify the detection of an associative and numerically indexed data by checking if the table class the behaviour was attached to, had a matching entity, which would then mean it's trying to save an uploaded entity, rather than an entity field.

I guess the check isn't working, because it's getting into the entity block for when it's a field.

There are methods around for detecting numerically indexed data, so that might be an option.

I'd be happy to review a pull request on the `develop` branch if you have some time to look into it. It'll need a test case too, to prevent a regression, as this has highlighted a hole in the test suite, despite me adding some tests for the new functionality.
